server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index lafan.dashboard.html;

    location / {
        try_files $uri $uri/ /lafan.dashboard.html;
    }

    location ~* \.(jpg|jpeg|png|gif|svg|webp|ico)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
